In [1]:
from numpy import mean
from numpy import std
from pandas import read_csv
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [2]:
# load the dataset
dataset = read_csv('Downloads/AllDataSet/training.csv')
testset = read_csv('Downloads/AllDataSet/testing.csv')
data = dataset.values
test = testset.values
X = data[:, :-1].astype(str)
y = data[:, -1].astype(str)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)
X2 = test[:, :1].astype(str)
x_test = test[:, 1:-1].astype(str)

# ordinal encode input variables
ordinal_encoder = OrdinalEncoder(handle_unknown='ignore')
ordinal_encoder.fit(X_train)
X_train = ordinal_encoder.transform(X_train)
X_test = ordinal_encoder.transform(X_test)
x_test = ordinal_encoder.transform(x_test)

# ordinal encode target variable
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(y_train)

# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)

In [3]:
#Logistic Regression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
logmodel = LogisticRegression(solver='lbfgs', max_iter=1000)
print(logmodel.fit(X_train,y_train))          
y_pred = logmodel.predict(X_test)
y_pred2 = logmodel.predict(x_test)
confusion_matrix = confusion_matrix(y_test,y_pred)
print(confusion_matrix)
print(classification_report(y_test,y_pred))
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy: %.2f' % (accuracy*100))
record_id = pd.DataFrame(X2, columns = ['record_id'])
df = pd.DataFrame(y_pred2, columns = ['conversion_fraud'])
result = pd.concat([record_id, df], axis=1, join='inner')
result.to_csv('Downloads/AllDataSet/Result/lr_result.csv', index=False)

LogisticRegression(max_iter=1000)
[[120   0]
 [ 22  21]]
              precision    recall  f1-score   support

       False       0.85      1.00      0.92       120
        True       1.00      0.49      0.66        43

    accuracy                           0.87       163
   macro avg       0.92      0.74      0.79       163
weighted avg       0.89      0.87      0.85       163

Accuracy: 86.50


C:\Users\Manisha\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [4]:
#Support Vector Machine
svmmodel = svm.LinearSVC(dual=False)
print(svmmodel.fit(X_train,y_train))          
y_pred=svmmodel.predict(X_test)
y_pred2=svmmodel.predict(x_test)
from sklearn.metrics import confusion_matrix
confusion_matrix=confusion_matrix(y_test,y_pred)
print(confusion_matrix)
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy: %.2f' % (accuracy*100))
record_id = pd.DataFrame(X2, columns = ['record_id'])
df = pd.DataFrame(y_pred2, columns = ['conversion_fraud'])
result = pd.concat([record_id, df], axis=1, join='inner')
result.to_csv('Downloads/AllDataSet/Result/svm_result.csv', index=False)

LinearSVC(dual=False)
[[120   0]
 [ 22  21]]
              precision    recall  f1-score   support

       False       0.85      1.00      0.92       120
        True       1.00      0.49      0.66        43

    accuracy                           0.87       163
   macro avg       0.92      0.74      0.79       163
weighted avg       0.89      0.87      0.85       163

Accuracy: 86.50


In [5]:
#KNN
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
y_pred2 = classifier.predict(x_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy: %.2f' % (accuracy*100))
record_id = pd.DataFrame(X2, columns = ['record_id'])
df = pd.DataFrame(y_pred2, columns = ['conversion_fraud'])
result = pd.concat([record_id, df], axis=1, join='inner')
result.to_csv('Downloads/AllDataSet/Result/knn_result.csv', index=False)

[[117   3]
 [ 16  27]]
              precision    recall  f1-score   support

       False       0.88      0.97      0.92       120
        True       0.90      0.63      0.74        43

    accuracy                           0.88       163
   macro avg       0.89      0.80      0.83       163
weighted avg       0.89      0.88      0.88       163

Accuracy: 88.34
